import { typeDefs } from "./graphql-schema";
import { ApolloServer } from "apollo-server";
import { v1 as neo4j } from "neo4j-driver";
import { makeAugmentedSchema } from "neo4j-graphql-js";
import dotenv from "dotenv";
import AWS from 'aws-sdk';
AWS.config.update({
  region: 'ap-south-1'
});






// set environment variables from ../.env
dotenv.config();

/*
 * Create an executable GraphQL schema object from GraphQL type definitions
 * including autogenerated queries and mutations.
 * Optionally a config object can be included to specify which types to include
 * in generated queries and/or mutations. Read more in the docs:
 * https://grandstack.io/docs/neo4j-graphql-js-api.html#makeaugmentedschemaoptions-graphqlschema
 */

const schema = makeAugmentedSchema({
  typeDefs,
  
});

/*
 * Create a Neo4j driver instance to connect to the database
 * using credentials specified as environment variables
 * with fallback to defaults
 */
const driver = neo4j.driver(
  process.env.NEO4J_URI || "bolt://localhost:7687",
  neo4j.auth.basic(
    process.env.NEO4J_USER || "neo4j",
    process.env.NEO4J_PASSWORD || "letmein"
  )
);


const middleware = async(req, res, next) => {
  try {
    const token = req.headers.authorization;
    if (token) {
      var params = {
        AccessToken:token.replace('Bearer ', '')
      };
      var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();
      const user = await cognitoidentityserviceprovider.getUser(params);
      console.log(user);
      next();
    } else {
      res.status(401).send({ message: 'You must supply a JWT for authorization!' });
    }
  } catch (error) {
    res.status(401).send({ message: 'You must supply a JWT for authorization!' });
  } 
};

/*
 * Create a new ApolloServer instance, serving the GraphQL schema
 * created using makeAugmentedSchema above and injecting the Neo4j driver
 * instance into the context object so it is available in the
 * generated resolvers to connect to the database.
 */
const server = new ApolloServer({
  context: async ({ req,driver }) => {
    const token = req.headers.authorization;
    if(token){
      
    }
   
    return {
      myProperty: true
    };
  },
  schema: schema,
  introspection: true, // enables introspection of the schema
  playground: true, // enables the actual playground
});

server.listen(process.env.GRAPHQL_LISTEN_PORT, "0.0.0.0").then(({ url }) => {
  console.log(`GraphQL API ready at ${url}`);
});
